version: '3'
volumes:
  tags-api-db:
services:
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/marley-spoon-recipes
    ports:
      - "3000:3000"
